config/routes.rb
Blocipedia::Application.routes.draw do
  
  devise_for :users
  resources :wikis do 
    get :manage_collaborators, on: :member
    post :save_collaborators, on: :member
  end
  
  resources :users
  resources :charges
  
  get "welcome/index"
  get "welcome/about"

  root :to => 'welcome#index'
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    new_record?
  end

  attr_accessible :body, :title, :public
  belongs_to :user
  validates :title, length: {minimum: 5, message: "your title is too short"}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :user, presence: true #do i need this here?  shouldn't a wiki always have a user if a requirement is current_user = true?

  scope :visible_to, lambda { |user| } #if user is premium, no filters, if not => filter by public == true
  
  scope :public, where(public: true) #make Wiki.public possible
  
  default_scope order('created_at DESC')

  has_many :collaborators

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  respond_to :html, :js

  def index
    @wikis = current_user.nil? ? Wiki.public.order('created_at desc') : (Wiki.public.to_a + current_user.collaborations + current_user.wikis)
  end

  def new
    @wiki = Wiki.new
    authorize! :create, @wiki, message: "You must be authorized to make a new wiki"
  end

  def show
    @wiki = Wiki.find(params[:id])
    if request.path != wiki_path(@wiki)             #friendly_id gem
      redirect_to @wiki, status: :moved_permanently #friendly_id gem
    end                                             #friendly_id gem
    authorize! :read, @wiki, message: "You must be authorized to view Wikis"
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You must be authorized to edit Wikis"
  end

  def create
    @wiki = Wiki.new(params[:wiki])
    @wiki.user = current_user
    authorize! :create, @wiki
    if @wiki.save
      flash[:notice] = "Wiki Saved Successfully!"
      redirect_to @wiki
    else
      Rails.logger.info @wiki.errors.full_messages
      flash[:error] = "Error saving wiki :("
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize! :update, @wiki, message: "You must be authorized to edit Wikis"
    if @wiki.update_attributes(params[:wiki])
      flash[:notice] = "updated successfully!"
      redirect_to @wiki
    else 
      flash[:error] = "You must be logged in to update!"
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize! :destroy, @wiki, message: "You must be authorized to delete this"
    if @wiki.destroy
 #     flash[:notice] = "destroyed successfully"
    else
      flash[:error] = "unable to delete!"
    end
    
    respond_with(@wiki) do |f|
      f.html { redirect_to user_path(current_user) }
    end
  end

  def manage_collaborators
    @wiki = Wiki.find(params[:id])
    @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
  end

  def save_collaborators
    @wiki = Wiki.find(params[:id])
    success = false
    current_collaborators = @wiki.collaborators.map(&:id)
    Rails.logger.info ">>>> #{current_collaborators.inspect}"
    
    if params["collaborator_id"].nil?
      current_collaborators.each do |collab_id| 
        Collaborator.destroy(collab_id)
        success = true
      end
    else
      params["collaborator_id"].each do |collaborator_id|
      user = User.find(collaborator_id)
      success = Collaborator.create(user: user, wiki: @wiki)
      end
    end
    Rails.logger.info "<<<< #{current_collaborators.inspect}"
    if success && params["collaborator_id"]
      current_collaborators.each do |collab_id| 
        Collaborator.destroy(collab_id)
      end
      Rails.logger.info "<<<< #{@wiki.collaborators.map(&:id)}"
      flash[:notice] = "successfully saved collaborators!"
      redirect_to @wiki
    elsif success && params["collaborator_id"].nil?
      flash[:notice] = "removed all collaborators!"
      redirect_to @wiki
      
    else
      flash[:error] = "unable to save collaborators"
      redirect_to @wiki
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper

  def has_collaborator(wiki, user)
    wiki.collaborators.map(&:user_id).include?(user.id)
  end

  def sortable(column, title = nil)  
    title ||= column.titleize  
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"  
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end  

end

app/views/wikis/_form.html.erb
<div class="control-group">
  <%= f.label :title %>
  <div class="controls">
    <%= f.text_field :title, :autofocus => true, placeholder: 'Enter Title' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :body %>
  <div class="controls">
    <%= f.text_area :body %>
  </div>
</div>


<% if current_user.id == @wiki.user_id %>
<div class="control-group">
    <%= f.label :public %>
    <div class="controls">
      <%= f.check_box :public %>Public Wiki (You must be a premium member to create a private wiki)
    </div>
  </div>

<% end %>
<%= link_to "preview", "#", :id => "previewLink" %>

 <div id="epiceditor"></div>

app/views/wikis/_wikis.html.erb
<table class="table table-bordered sortable">
  <thead>
    <tr>
      <th>Title</th>
      <th>Public or Private?</th>
      <th>Updated At</th>
      <th>Options</td>
    </tr>
  </thead>
  <tbody>
    <% @wikis.each do |wiki| %>
      <tr id="<%= dom_id(wiki) %>">
        <td>
          <%= wiki.title %>   
        </td>
        <td>
          <% if wiki.public? %>
          Public
          <% else %>
          Private
          <% end %>
        </td>
        <td data-value="<%= wiki.updated_at %>">
          <i><%= time_ago_in_words(wiki.updated_at) %> ago</i>
        </td>
        <td>
          <%= link_to "Edit", edit_wiki_path(wiki) %> | 
          <%= link_to "Manage Collab", manage_collaborators_wiki_path(wiki) %> | 
          <%= link_to "Delete", wiki_path(wiki), method: :delete, data: { confirm: "Are you sure you want to delete the Wiki: '#{wiki.title}'"},remote: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wikis/add_collaborators.html.erb
<h1>Add Collaborators to your private wiki</h1>
<%= form_for @wiki, url: save_collaborators_wiki_path, method: :post do |user| %>
  <div class="span5">
    <table>
    <thead>
      <tr>
        <th>User Name</th>
        <th>Email</th>
        <th>Add Collaborator?</th>
      </tr>
    </thead>
     <tbody> 
      <% @users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.email %></td>
          <td>
            <%= check_box_tag "collaborator_id[]", u.id, has_collaborator(@wiki, u) %>
          </td>
        </tr> 
    <% end %>
    </table>
  </div>
  <div class="span5">
    <%= user.submit 'Save collaborators' %>
  </div>
<% end %>

app/views/wikis/destroy.js.erb
$("#wiki_<%= @wiki.id %>").hide();

app/views/wikis/edit.html.erb
<!-- <%= content_for :head do %>
  <test>Hi!</test>
  <%= stylesheet_link_tag 'wikis' %>
<% end %> -->

<div class="container">
  <div class="span5">
    <%= form_for @wiki do |f| %>
      <%= render 'form', :f => f %>
      <div class="control-group">
        <%= f.submit "Save!", class: 'btn', :id => "submitBtn" %></div>
        <%= link_to "Manage Collaborator", manage_collaborators_wiki_path(@wiki), class: 'btn' %>
    <% end %>
  </div>
  <div class="span5">
    <h1>EDIT VIEW HERE</h1>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="span5">
  <h1> Wiki Index </h1>
  <p>Show all wikis</p>
  <% @wikis.each do |wiki| %>
    <h2><%= markdown link_to wiki.title, wiki %></h2> - <%= wiki.public? %> - <%= wiki.user_id %>
    <small><%= markdown wiki.body %></small>  
  <% end %>
</div>

<div class="span5">
  <h1>Want to make a new wiki?</h1>
  <%= link_to "Make New Wiki!", new_wiki_path, class:'btn btn-large' %>
</div>

app/views/wikis/manage_collaborators.html.erb
<h1>Manage Collaborators For "<%= @wiki.title %>:"!</h1>
<%= form_for @wiki, url: save_collaborators_wiki_path, method: :post do |user| %>
  <div class="span5">
    <table>
    <thead>
      <tr>
        <th>User Name</th>
        <th>Email</th>
        <th>Add Collaborator?</th>
      </tr>
    </thead>
     <tbody> 
      <% @users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.email %></td>
          <td>
            <%= check_box_tag "collaborator_id[]", u.id, has_collaborator(@wiki, u) %>
          </td>
        </tr> 
    <% end %>
    </table>
  </div>
  <div class="span5">
    <%= user.submit 'Save collaborators' %>
  </div>
<% end %>

app/views/wikis/new.html.erb
<!--<%= content_for :head do %>
  <test>Hi!</test>
  <%= stylesheet_link_tag 'wikis' %>
<% end %>-->

<h2>New Wiki!</h2>

<%= form_for @wiki do |f| %>
 <%= render 'form', :f => f %>

  <div class="control-group">
    <%= f.submit "Create Wiki!", class: 'btn', :id => "submitBtn" %></div>
<% end %>

app/views/wikis/show.html.erb
<h1><%= markdown @wiki.title %></h1>
  <small>
    <p><i>Updated about <%= time_ago_in_words(@wiki.updated_at) %> ago</i></p> - 
    <% if @wiki.public? %>
      Public
      <% else %>
      Private
      <% end %>

  </small>
<%= markdown @wiki.body %>

<%= link_to "Edit Wiki", edit_wiki_path(@wiki) %>
<p>
<% if current_user %>
  <% if @wiki.user_id == current_user.id %>
  <%= link_to "Manage Collaborators", manage_collaborators_wiki_path(@wiki) %>
  </p>
  <% end %>
<% end %>


<%= @current_collaborators.inspect %>