config/routes.rb
Blocipedia::Application.routes.draw do
  
  devise_for :users
  resources :wikis do 
    get :manage_collaborators, on: :member
    post :save_collaborators, on: :member
  end
  
  resources :users
  resources :charges
  
  get "welcome/index"
  get "welcome/about"

  root :to => 'welcome#index'
end

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Blocipedia</a>
      <ul class="nav">
        <li class="divider-vertical"></li>
        <li class="active"><%= link_to "Home", welcome_index_path %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
      </ul>
      <ul class="pull-right nav">
    
      <% if current_user %>
        <% if current_user.role == "free" %>
          <li><%= link_to "Upgrade", new_charge_path %></li>
        <% end %>    
        <li><%= link_to "My Profile", edit_user_registration_path %></li>
        <li><%= link_to "My Wikis", current_user %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
<!-- modify css for edit view
  <%- if content_for?(:head) -%>
    <%= yield :head %>
  <% end %> -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <%= render 'layouts/header' %>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
  </div>
  
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <%= yield %>
  </body>
</html>